name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.5'

    - name: Test With Coverage
      run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Add coverage as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./coverage.txt